### ISSUE TITLE
App Store Rejection

### ISSUE THREAD

**Issue by RealNerd** [javerous/SMCryptoFile#1]
Hello,

I love this library! However, when we submitted our app to the store for review, the static analyzer rejected the app for exposing the private symbols **CCCryptorEncryptDataBlock**, **CCCryptorDecryptDataBlock**, **CCRandomCopyBytes** and **kCCRandomDefault**.

Have you had any experience with this? Do you know if we can use this library in an App Store app?

**Comment by javerous** [comment]
Hi RealNerd. Bad new :(

The XTS OS X functions are in a SPI header, and considered as "work in progress" (and so willing to be public at the end). They didn't changed anything since 10.7 (apparently) in XTS, but they still don't publish the API. I don't know what they are waiting.

I try to push them to quick up things, but they never answer. That's Apple...

I don't develop for MAS, so I never had the problem.

Open a bug report on Apple bug reporter. The more people complain, the more we have chance to be listened.

Sorry for that.

**Comment by RealNerd** [comment]
Thank you for your response. Hopefully soon we will be able to use these functions. I'll file a bug with Apple!

Blake

**Comment by javerous** [comment]
Yes. I'm going to open a DTS, perhaps this will help.

**Comment by javerous** [comment]
A possible workaround would be to use dlopen / dlsym to load this functions, so they can't check automatically that we are using them. Can be a middle term solution, before they decide to release the thing.

**Comment by javerous** [comment]
For information, Apple answered "It is Apple policy not to comment on future bug fixes and enhancements." to my DTS. Endpoint.

**Comment by RealNerd** [comment]
Thank you for taking some time on this!

**Comment by javerous** [comment]
You are welcome. I implemented the dolmen / dlsym bypass in commit 50c0c9574b7355d278b8491913eec1162c333c1f.

**Comment by RealNerd** [comment]
Wow! Thank you!!

**Comment by RealNerd** [comment]
Just wanted to let you know that we resubmitted with your update and it went through. Thanks again!
